[package]
name = "RustAOC"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
string-builder = "0.2.0"
disjoint = "0.8.0"
bimap = "0.6.3"
itertools = "0.14.0"
microlp = "0.2.11"
bit-set = "0.8.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
